name: Check if given PR is a valid RFC PR

inputs:
  given-pr-number:
    description: Given PR number to be checked against
    required: true

outputs:
  result:
    description: Result of the validation
    value: ${{ steps.validate-current-pr.outputs.result }}

runs:
  using: composite
  steps:
    - name: Checkout current branch
      uses: actions/checkout@v4

    - name: Validate current PR
      id: validate-current-pr
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const prNumber = Number("${{ inputs.given-pr-number }}");
          const prTitle = context.payload.pull_request.title;

          const REGEX_VALID_RFC_PR_TITLE = /^(rfc\(([a-z]|\-)+\))\:\s(\w|\s)+$/;

          const validationChecks = {
            titleFormatValid: true,
            directorateExists: true,
            documentExists: true,
            documentNameFormatValid: true,
            documentNameLengthOk: true,
          };

          if (!REGEX_VALID_RFC_PR_TITLE.test(prTitle)) {
            validationChecks.titlePassed = false;
          }

          if (Object.values(validationChecks).every((check) => check)) {
            return 'true';
          }

          return JSON.stringify(validationChecks);

      # PR directorate?
      # return JSON.stringify(validationChecks);
