name: Retrieve the RFC Registry metadata

input:
  output-var-name:
    description: Output variable name to store the stringified registry metadata
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout latest main
      uses: actions/checkout@v4
      with:
        ref: main
        sparse-checkout: |
          .repo

    - name: Fetch and cache metadata
      uses: actions/github-script@v7
      with:
        script: |
          let jsonRfcRegistry;

          try {
            jsonRfcRegistry = require('.repo/rfc-registry.json');
          } catch (e) {
            core.setFailed("RFC registry file is missing");
            return;
          }

          const { rfcPRsRegistered } = jsonRfcRegistry;
          if (!Array.isArray(rfcPRsRegistered)) {
            core.setFailed("RFC PR registery entry is missing!");
            return;
          }

          core.setOutput("${{ inputs.output-var-name }}", JSON.stringify(rfcPRsRegistered));
