name: Retrieve the RFC Registry metadata

runs:
  using: "composite"
  steps:
    - name: Checkout latest main
      uses: actions/checkout@v4
      with:
        ref: main
        sparse-checkout: |
          .repo

    - name: Fetch and cache metadata
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          let jsonRfcRegistry;

          try {
            jsonRfcRegistry = require('.repo/rfc-registry.json');
          } catch (e) {
            core.setFailed("RFC registry file is missing");
            return;
          }

          const { rfcPRsRegistered } = jsonRfcRegistry;
          if (!Array.isArray(rfcPRsRegistered)) {
            core.setFailed("RFC PR registery entry is missing!");
            return;
          }

          return JSON.stringify({ rfcPRsRegistered });
