name: Update the RFC Registry with the given PR number

input:
  given-pr-number:
    description: Given PR number to be checked against
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout latest main
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Update the registry
      id: update-registry
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = Number("${{ inputs.given-pr-number }}");

          const fs = require('fs');
          const path = require('path');

          const registryPath = path.join(process.env.GITHUB_WORKSPACE, '.repo/rfc-registry.json');

          let jsonRfcRegistry;
          try {
            jsonRfcRegistry = require(registryPath);
          } catch (e) {
            core.setFailed("RFC registry file is missing");
            return;
          }

          const { rfcPRsRegistered } = jsonRfcRegistry;
          if (!Array.isArray(rfcPRsRegistered)) {
            core.setFailed("RFC PR registery entry is missing!");
            return;
          }

          if (rfcPRsRegistered.includes(prNumber)) {
            core.setFailed("Given PR number is already registered!");
            return;
          }

          rfcPRsRegistered.push(prNumber);

          fs.writeFileSync(registryPath, JSON.stringify(jsonRfcRegistry, null, 2));

    - name: Commit and push the updated registry
      id: commit-and-push
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "maintenance: update the RFC registry with PR number ${{ inputs.given-pr-number }}"
        title: "maintenance: update the RFC registry with PR number ${{ inputs.given-pr-number }}"
        body: "(Auto generated by the Github Actions workflow)"

    - name: Auto-approve PR
      uses: juliangruber/approve-pull-request-action@v2
      with:
        github-token: ${{ secrets.PAT_ARUDEI_DEV_ALTEREGO }}
        number: ${{ steps.commit-and-push.outputs.pull-request-number }}

    - name: Merge PR
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.commit-and-push.outputs.pull-request-number }}
