name: Check if given PR is registered in the RFC Registry

input:
  given-pr-number:
    description: Given PR number to be checked against
    required: true

outputs:
  result:
    description: Boolean value indicating if the given PR number is registered or not
    required: true
    value: ${{ steps.check-if-pr-registered.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: retrieve-rfc-registry
      name: Retrieve RFC Registry metadata
      uses: ./.github/actions/retrieve-rfc-registry

    - name: Checkout current branch
      uses: actions/checkout@v4

    - name: Check if current PR number has been registered or not
      id: check-if-pr-registered
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const prNumber = Number("${{ inputs.given-pr-number }}");

          const rfcRegistry = JSON.parse("${{ steps.retrieve-rfc-registry.outputs.result }}");

          return rfcRegistry.rfcPRsRegistered.includes(prNumber);
