name: Hello Github Actions

on: [push]

jobs:
  do_something:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Check if workflow has been run before
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const jsonRfcRegistry = require('.repo/rfc-registry.json');
            console.log({jsonRfcRegistry})

      # console.log(process.cwd());

      # const jsonRfcRegistry = require('.repo/rfc_registry.json');

      # core.setOutput(JSON.stringify(jsonRfcRegistry, null, 2));

      # const prNumber = context.payload.pull_request.number;
      # const jsonRfcRegistry = require('./.repo/rfc_registry.json');

      # // Handle if not available

      # const { rfcPRsRegistered } = jsonRfcRegistry;

      # if (!Array.isArray(rfcPRsRegistered)) {
      #   // should be unreachable, file is missing
      #   core.setFailed("RFC registry file is missing");
      #   return;
      # }

      # const foundCurrentPRidx = rfcPRsRegistered.findIndex((pr) => pr.prNumber === prNumber);

      # if (foundCurrentPRidx < 0) {
      #   // handle registration make commit IF this is an RFC PR
      #   return;
      # }

      # // handle setting the PR (make comment?) IF this is an RFC PR

      # - name: Hello world
      #   run: |
      #     ls -al
      #     echo "Hello world"
