name: Hello Github Actions

on: [push]

jobs:
  do_something:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Hello world
        run: |
          ls -al >> $GITHUB_OUTPUT
          echo "Hello world"
