name: "[Pull Request] 1. Preparations"

# Only allows for one workflow run at a time as to avoid race conditions.
concurrency:
  group: ${{ github.workflow }}

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  does-pr-contains-valid-rfc:
    name: "Does current PR contain a valid RFC?"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    outputs:
      is-pr-registered: ${{ steps.check-is-pr-registered.outputs.is-pr-registered }}
      is-valid-rfc-pr: ${{ steps.check-is-valid-rfc-pr.outputs.is-valid-rfc-pr }}
    steps:
      - name: Checkout latest main
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: |
            .github
            .repo

      - id: check-is-pr-registered
        name: "Check if PR is registered in the RFC registry"
        uses: ./.github/actions/check-is-pr-registered
        with:
          given-pr-number: ${{ github.event.pull_request.number }}

      - id: check-is-valid-rfc-pr
        name: "Check if PR is a valid RFC"
        uses: ./.github/actions/check-is-valid-rfc-pr
        if: steps.check-is-pr-registered.outputs.result == 'false'

      - name: Setting up Job outputs
        run: |
          echo "is-pr-registered=${{ steps.check-is-pr-registered.outputs.result || false }}" >> $GITHUB_OUTPUT
          echo "is-valid-rfc-pr=${{ steps.check-is-valid-rfc-pr.outputs.result || false }}" >> $GITHUB_OUTPUT

          echo "::notice title=${{ github.job }} / Is PR registered?::${{ steps.check-is-pr-registered.outputs.result || 'false' }}"

          if [ "${{ steps.check-is-pr-registered.outputs.result }}" == "false" ]; then
            notice_msg="- ${{ steps.check-is-valid-rfc-pr.outputs.result == 'true' && 'Passed' || 'Failed' }}%0A"

            if [ "${{ steps.check-is-valid-rfc-pr.outputs.result }}" != "true" ]; then
              current_msg="- Validation failed on: ${{ steps.check-is-valid-rfc-pr.outputs.result }}"
              notice_msg="${notice_msg}${current_msg}%0A"
            fi

            echo "::notice title=${{ github.job }} / Is PR a valid RFC PR?::${notice_msg}"
          fi

  add-pr-to-rfc-registry:
    name: "Add current PR to the RFC registry"
    needs: does-pr-contains-valid-rfc
    if: needs.does-pr-contains-valid-rfc.outputs.is-pr-registered == false && needs.does-pr-contains-valid-rfc.outputs.is-valid-rfc-pr == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - id: update-rfc-registry-with-pr-number
        name: "Update the RFC registry with PR number"
        uses: ./.github/actions/update-rfc-registry-with-pr-number
        with:
          given-pr-number: ${{ github.event.pull_request.number }}
